#!/usr/bin/env python3
"""
Parse bitbake dependency graph output to extract SRC_URI and SRCREV per recipe.

Strategy:
  1. Read pn-buildlist (from `bitbake -g`) to get the list of recipes.
  2. For each recipe, run `bitbake -e <recipe>` and parse its SRC_URI / SRCREV.
  3. Filter for git:// based sources and output JSON.

Usage:
    python3 parse_bitbake_deps.py \
        --pn-buildlist <path>/pn-buildlist \
        --machine <machine>

Output: JSON array to stdout, one entry per git-based recipe.
"""

import argparse
import json
import os
import re
import subprocess
import sys


def parse_args():
    parser = argparse.ArgumentParser(
        description="Parse bitbake dependency graph to extract git-based SRC_URI and SRCREV."
    )
    parser.add_argument(
        "--pn-buildlist",
        required=True,
        help="Path to pn-buildlist file generated by 'bitbake -g'.",
    )
    parser.add_argument(
        "--machine",
        required=True,
        help="Target machine name (for metadata only).",
    )
    return parser.parse_args()


def read_file_lines(path):
    """Read file and return lines, stripping whitespace."""
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return [line.strip() for line in f if line.strip()]


def query_recipe_env(recipe_name):
    """
    Run `bitbake -e <recipe>` and extract SRC_URI and SRCREV.

    Returns dict with keys 'SRC_URI' and 'SRCREV', or empty dict on failure.
    """
    try:
        result = subprocess.run(
            ["bitbake", "-e", recipe_name],
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return {}

    if result.returncode != 0:
        return {}

    src_uri = ""
    srcrev = ""

    for line in result.stdout.splitlines():
        # bitbake -e outputs VAR="value" lines for final variable values
        if line.startswith("SRC_URI="):
            m = re.match(r'^SRC_URI="(.*)"$', line)
            if m:
                src_uri = m.group(1).strip()
        elif line.startswith("SRCREV="):
            m = re.match(r'^SRCREV="(.*)"$', line)
            if m:
                srcrev = m.group(1).strip()

    if not src_uri:
        return {}

    return {"SRC_URI": src_uri, "SRCREV": srcrev}


def extract_git_srcuris(src_uri_value):
    """
    Extract git:// URIs from a SRC_URI value.

    SRC_URI can contain multiple space-separated entries.
    We only care about git:// entries.

    Returns list of git URIs.
    """
    if not src_uri_value:
        return []

    entries = src_uri_value.split()
    git_entries = []
    current = None

    for entry in entries:
        if entry.startswith("git://"):
            if current:
                git_entries.append(current)
            current = entry
        elif current and "://" not in entry:
            # Append bare parameters (no scheme) to the current git URI.
            # Entries with a scheme (file://, http://, etc.) are separate
            # fetcher URIs and must not be appended.
            current = current + " " + entry
        # Non-git standalone entries (other scheme URIs) are ignored

    if current:
        git_entries.append(current)

    return git_entries


def extract_repo_name(git_uri):
    """
    Extract repository name from a git URI.

    git://github.com/openbmc/linux;protocol=https;branch=dev-6.6 -> linux
    """
    url_part = git_uri.split(";")[0]
    path = url_part.split(":")[-1]
    if path.startswith("//"):
        path = path[2:]

    repo_name = path.split("/")[-1]
    if repo_name.endswith(".git"):
        repo_name = repo_name[:-4]

    return repo_name


def convert_to_https_url(git_uri):
    """
    Convert a git:// URI to an https:// clone URL.

    git://github.com/openbmc/linux;protocol=https;branch=dev-6.6
    -> https://github.com/openbmc/linux
    """
    url_part = git_uri.split(";")[0]

    if url_part.startswith("git://"):
        rest = url_part[6:]
    elif url_part.startswith("https://"):
        return url_part
    elif url_part.startswith("ssh://"):
        rest = url_part[6:]
        if rest.startswith("git@"):
            rest = rest[4:]
        return "https://" + rest
    else:
        return url_part

    return "https://" + rest


def main():
    args = parse_args()

    if not os.path.isfile(args.pn_buildlist):
        print(f"Error: pn-buildlist not found: {args.pn_buildlist}", file=sys.stderr)
        sys.exit(1)

    recipe_names = read_file_lines(args.pn_buildlist)
    total = len(recipe_names)

    results = []
    seen_repos = set()

    for i, recipe in enumerate(recipe_names, 1):
        print(f"\rQuerying recipe {i}/{total}: {recipe}...", end="", file=sys.stderr)
        recipe_info = query_recipe_env(recipe)
        src_uri = recipe_info.get("SRC_URI", "")
        srcrev = recipe_info.get("SRCREV", "AUTOINC")

        git_uris = extract_git_srcuris(src_uri)
        if not git_uris:
            continue

        for git_uri in git_uris:
            repo_name = extract_repo_name(git_uri)

            if repo_name in seen_repos:
                continue
            seen_repos.add(repo_name)

            results.append(
                {
                    "name": repo_name,
                    "src_uri": git_uri,
                    "srcrev": srcrev if srcrev != "AUTOINC" else "${AUTOREV}",
                    "recipe": recipe,
                    "clone_url": convert_to_https_url(git_uri),
                }
            )

    print("", file=sys.stderr)  # newline after progress
    json.dump(results, sys.stdout, indent=2, ensure_ascii=False)
    print()


if __name__ == "__main__":
    main()
