#!/usr/bin/env python3
"""
Parse bitbake dependency graph output to extract SRC_URI and SRCREV per recipe.

Strategy (Tinfoil, default):
  1. Read pn-buildlist (from `bitbake -g`, ~570 recipes) as the recipe list.
  2. Use bitbake Tinfoil API to query SRC_URI/SRCREV in a single process.
     ~37s for ~570 recipes (vs ~17 min with bitbake -e × N).
     If pn-buildlist is absent, falls back to all_recipes() (~2750, slower).

Strategy (legacy, --pn-buildlist):
  1. Read pn-buildlist (from `bitbake -g`) to get the list of recipes.
  2. For each recipe, run `bitbake -e <recipe>` and parse its SRC_URI / SRCREV.
  3. Filter for git:// based sources and output JSON.

Usage:
    # Preferred: Tinfoil (requires bitbake environment)
    python3 parse_bitbake_deps.py --build-dir <path> --machine <machine>

    # Legacy fallback: bitbake -e per recipe
    python3 parse_bitbake_deps.py --pn-buildlist <path> --machine <machine>

Output: JSON array to stdout, one entry per git-based recipe.
"""

import argparse
import json
import os
import re
import signal
import subprocess
import sys


def parse_args():
    parser = argparse.ArgumentParser(
        description="Parse bitbake dependency graph to extract git-based SRC_URI and SRCREV."
    )
    # Tinfoil mode (default)
    parser.add_argument(
        "--build-dir",
        default=None,
        help="Path to bitbake build directory (containing conf/bblayers.conf). "
             "Enables Tinfoil mode (fast, single process).",
    )
    # Legacy mode (fallback)
    parser.add_argument(
        "--pn-buildlist",
        default=None,
        help="Path to pn-buildlist file generated by 'bitbake -g'. "
             "Enables legacy mode (bitbake -e per recipe, slower).",
    )
    parser.add_argument(
        "--machine",
        required=True,
        help="Target machine name (for metadata only).",
    )
    return parser.parse_args()


# === Shared helpers ===


def extract_git_srcuris(src_uri_value):
    """
    Extract git:// URIs from a SRC_URI value.

    SRC_URI can contain multiple space-separated entries.
    We only care about git:// entries.

    Returns list of git URIs.
    """
    if not src_uri_value:
        return []

    entries = src_uri_value.split()
    git_entries = []
    current = None

    for entry in entries:
        if entry.startswith("git://"):
            if current:
                git_entries.append(current)
            current = entry
        elif current and "://" not in entry:
            # Append bare parameters (no scheme) to the current git URI.
            # Entries with a scheme (file://, http://, etc.) are separate
            # fetcher URIs and must not be appended.
            current = current + " " + entry
        # Non-git standalone entries (other scheme URIs) are ignored

    if current:
        git_entries.append(current)

    return git_entries


def extract_repo_name(git_uri):
    """
    Extract repository name from a git URI.

    git://github.com/openbmc/linux;protocol=https;branch=dev-6.6 -> linux
    """
    url_part = git_uri.split(";")[0]
    path = url_part.split(":")[-1]
    if path.startswith("//"):
        path = path[2:]

    repo_name = path.split("/")[-1]
    if repo_name.endswith(".git"):
        repo_name = repo_name[:-4]

    return repo_name


def convert_to_https_url(git_uri):
    """
    Convert a git:// URI to an https:// clone URL.

    git://github.com/openbmc/linux;protocol=https;branch=dev-6.6
    -> https://github.com/openbmc/linux
    """
    url_part = git_uri.split(";")[0]

    if url_part.startswith("git://"):
        rest = url_part[6:]
        # Handle malformed git://git@host/path -> host/path
        if rest.startswith("git@"):
            rest = rest[4:].lstrip("/")
        if ":" in rest and not rest.startswith("["):
            # host:path format -> host/path
            rest = rest.replace(":", "/", 1)
        return "https://" + rest
    elif url_part.startswith("https://"):
        return url_part
    elif url_part.startswith("ssh://"):
        rest = url_part[6:]
        if rest.startswith("git@"):
            rest = rest[4:]
        return "https://" + rest
    else:
        return url_part


def _build_result_entry(git_uri, srcrev, recipe):
    """Build a single deps.json entry from a git URI and metadata."""
    repo_name = extract_repo_name(git_uri)

    # Extract branch from SRC_URI parameters
    branch = ""
    for param in git_uri.split(";")[1:]:
        if param.startswith("branch="):
            branch = param.split("=", 1)[1].strip('"').strip("'")
            break

    return {
        "name": repo_name,
        "src_uri": git_uri,
        "srcrev": srcrev if srcrev not in ("AUTOINC", "INVALID", "${AUTOREV}") else "${AUTOREV}",
        "recipe": recipe,
        "clone_url": convert_to_https_url(git_uri),
        "branch": branch,
    }


# === Tinfoil mode (fast, default) ===


def _extract_git_deps(src_uri, srcrev, recipe, seen_repos, results):
    """Extract git-based deps from a recipe's SRC_URI, dedup by repo name."""
    git_uris = extract_git_srcuris(src_uri)
    for git_uri in git_uris:
        repo_name = extract_repo_name(git_uri)
        if repo_name in seen_repos:
            continue
        seen_repos.add(repo_name)
        results.append(_build_result_entry(git_uri, srcrev, recipe))


def query_deps_tinfoil(build_dir):
    """
    Use bitbake Tinfoil API to query SRC_URI/SRCREV in a single process.

    If pn-buildlist exists (from `bitbake -g`), only queries those ~570 recipes.
    Otherwise falls back to all_recipes() (slower, ~2750 target recipes).

    Returns list of deps entries for git-based recipes.
    """
    build_dir = os.path.abspath(build_dir)
    # build_dir is typically <openbmc>/build/<machine>
    openbmc_dir = os.path.dirname(os.path.dirname(build_dir))
    bitbake_lib = os.path.join(openbmc_dir, "bitbake", "lib")

    if not os.path.isdir(bitbake_lib):
        print(
            f"Error: bitbake lib not found at {bitbake_lib}. "
            f"Ensure --build-dir points to a valid build directory.",
            file=sys.stderr,
        )
        sys.exit(1)

    sys.path.insert(0, bitbake_lib)

    try:
        from bb.tinfoil import Tinfoil
    except ImportError:
        print(
            f"Error: cannot import bb.tinfoil from {bitbake_lib}. "
            f"Ensure bitbake is present in the OpenBMC tree.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Determine recipe list: prefer pn-buildlist (target deps only, ~570)
    # over all_recipes() (~4492, even after filtering ~2750).
    pn_buildlist = os.path.join(build_dir, "pn-buildlist")
    if os.path.isfile(pn_buildlist):
        with open(pn_buildlist, "r", encoding="utf-8", errors="replace") as f:
            recipe_names = [line.strip() for line in f if line.strip()]
        print(
            f"Using pn-buildlist ({len(recipe_names)} recipes from bitbake -g).",
            file=sys.stderr,
        )
    else:
        recipe_names = None
        print(
            "pn-buildlist not found; will enumerate all recipes via Tinfoil.",
            file=sys.stderr,
        )

    results = []
    seen_repos = set()
    errors = 0

    # Tinfoil.prepare() spams stdout with cache/parsing logs.
    # Save real stdout, redirect to stderr during Tinfoil lifetime.
    real_stdout = sys.stdout
    sys.stdout = sys.stderr

    try:
        with Tinfoil() as tinfoil:
            print("Initializing Tinfoil (loading bitbake cache)...", file=sys.stderr)
            tinfoil.prepare(config_only=False)

            if recipe_names is not None:
                # Mode A: query only pn-buildlist recipes (~570)
                total = len(recipe_names)
                for i, pn in enumerate(recipe_names, 1):
                    print(
                        f"\rQuerying recipe {i}/{total}: {pn}...",
                        end="",
                        file=sys.stderr,
                    )
                    try:
                        d = tinfoil.parse_recipe(pn)
                    except Exception:
                        errors += 1
                        continue
                    if d is None:
                        errors += 1
                        continue
                    _extract_git_deps(
                        d.getVar("SRC_URI") or "",
                        d.getVar("SRCREV") or "",
                        pn, seen_repos, results,
                    )
            else:
                # Mode B: enumerate all_recipes(), skip native/sdk/cross variants
                # PN patterns: foo-native, foo-cross, foo-crosssdk (suffix)
                #              nativesdk-foo, cross-foo (prefix)
                # Both endswith and startswith checks are applied to catch all.
                _skip_suffix = ("-native", "-cross", "-crosssdk")
                _skip_prefix = ("nativesdk-", "cross-")
                recipe_list = [
                    r
                    for r in tinfoil.all_recipes()
                    if not (r.pn.endswith(_skip_suffix) or r.pn.startswith(_skip_prefix))
                ]
                total = len(recipe_list)
                print(f"Loaded {total} target recipes.", file=sys.stderr)

                for i, recipe in enumerate(recipe_list, 1):
                    pn = recipe.pn
                    print(
                        f"\rQuerying recipe {i}/{total}: {pn}...",
                        end="",
                        file=sys.stderr,
                    )
                    try:
                        d = tinfoil.parse_recipe(pn)
                    except Exception:
                        errors += 1
                        continue
                    if d is None:
                        errors += 1
                        continue
                    _extract_git_deps(
                        d.getVar("SRC_URI") or "",
                        d.getVar("SRCREV") or "",
                        pn, seen_repos, results,
                    )
    finally:
        sys.stdout = real_stdout

    print("", file=sys.stderr)  # newline after progress

    if errors > 0:
        print(
            f"Warning: {errors} recipes failed to parse (skipped).",
            file=sys.stderr,
        )

    return results


# === Legacy mode (bitbake -e per recipe, fallback) ===


def query_recipe_env(recipe_name):
    """
    Run `bitbake -e <recipe>` and extract SRC_URI and SRCREV.

    Returns dict with keys 'SRC_URI' and 'SRCREV', or empty dict on failure.
    """
    try:
        result = subprocess.run(
            ["bitbake", "-e", recipe_name],
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return {}

    if result.returncode != 0:
        return {}

    src_uri = ""
    srcrev = ""

    for line in result.stdout.splitlines():
        # bitbake -e outputs VAR="value" lines for final variable values
        if line.startswith("SRC_URI="):
            m = re.match(r'^SRC_URI="(.*)"$', line)
            if m:
                src_uri = m.group(1).strip()
        elif line.startswith("SRCREV="):
            m = re.match(r'^SRCREV="(.*)"$', line)
            if m:
                srcrev = m.group(1).strip()

    if not src_uri:
        return {}

    return {"SRC_URI": src_uri, "SRCREV": srcrev}


def query_deps_legacy(pn_buildlist_path):
    """
    Legacy mode: read pn-buildlist and query each recipe via bitbake -e.

    Returns list of deps entries for git-based recipes.
    """
    if not os.path.isfile(pn_buildlist_path):
        print(f"Error: pn-buildlist not found: {pn_buildlist_path}", file=sys.stderr)
        sys.exit(1)

    with open(pn_buildlist_path, "r", encoding="utf-8", errors="replace") as f:
        recipe_names = [line.strip() for line in f if line.strip()]

    total = len(recipe_names)

    results = []
    seen_repos = set()

    for i, recipe in enumerate(recipe_names, 1):
        print(f"\rQuerying recipe {i}/{total}: {recipe}...", end="", file=sys.stderr)
        recipe_info = query_recipe_env(recipe)
        src_uri = recipe_info.get("SRC_URI", "")
        srcrev = recipe_info.get("SRCREV", "AUTOINC")

        _extract_git_deps(src_uri, srcrev, recipe, seen_repos, results)

    print("", file=sys.stderr)  # newline after progress
    return results


# === Main ===


def main():
    args = parse_args()

    # On SIGINT (ctrl+C), exit silently without writing partial output.
    # The caller (ob) writes to a .tmp file and renames on success,
    # so a signal here means the .tmp gets discarded.
    signal.signal(signal.SIGINT, lambda _sig, _frame: sys.exit(130))

    if args.build_dir:
        # Tinfoil mode (fast)
        results = query_deps_tinfoil(args.build_dir)
    elif args.pn_buildlist:
        # Legacy mode (fallback)
        results = query_deps_legacy(args.pn_buildlist)
    else:
        print(
            "Error: either --build-dir (Tinfoil, recommended) "
            "or --pn-buildlist (legacy) must be specified.",
            file=sys.stderr,
        )
        sys.exit(1)

    json.dump(results, sys.stdout, indent=2, ensure_ascii=False)
    print()


if __name__ == "__main__":
    main()
