#!/usr/bin/env python3
"""
Parse bitbake dependency graph output to extract SRC_URI and SRCREV per recipe.

Usage:
    python3 parse_bitbake_deps.py \
        --pn-buildlist <path>/pn-buildlist \
        --bitbake-env <path>/bitbake-e-output \
        --machine <machine>

Output: JSON array to stdout, one entry per git-based recipe.
"""

import argparse
import json
import os
import re
import sys
from urllib.parse import urlparse


def parse_args():
    parser = argparse.ArgumentParser(
        description="Parse bitbake dependency graph to extract git-based SRC_URI and SRCREV."
    )
    parser.add_argument(
        "--pn-buildlist",
        required=True,
        help="Path to pn-buildlist file generated by 'bitbake -g'.",
    )
    parser.add_argument(
        "--bitbake-env",
        required=True,
        help="Path to file containing 'bitbake -e' output.",
    )
    parser.add_argument(
        "--machine",
        required=True,
        help="Target machine name (for metadata only).",
    )
    return parser.parse_args()


def read_file_lines(path):
    """Read file and return lines, stripping whitespace."""
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return [line.strip() for line in f if line.strip()]


def parse_bitbake_env(env_path):
    """
    Parse bitbake -e output to extract per-recipe SRC_URI and SRCREV.

    bitbake -e output contains lines like:
        # $SRC_URI [3 operations]
        SRC_URI="git://github.com/openbmc/linux;protocol=https;branch=dev-6.6  "
        # $SRCREV [2 operations]
        SRCREV="abc123..."

    We collect variable assignments that follow comment headers with recipe context.
    """
    recipes = {}
    current_var = None
    current_recipe = None

    with open(env_path, "r", encoding="utf-8", errors="replace") as f:
        for raw_line in f:
            line = raw_line.rstrip("\n")

            # Detect variable comment: # $VARNAME [N operations]
            var_match = re.match(r"^#\s+\$(\w+)\s+\[\d+\s+operations?\]", line)
            if var_match:
                current_var = var_match.group(1)
                continue

            # Detect assignment: VARNAME="value"  or VARNAME="value # comment"
            # Also handle: VARNAME="multi\nline"  but bitbake -e usually puts it on one line
            if current_var and line.startswith(current_var + "="):
                val_match = re.match(r'^%s="(.*)"$' % re.escape(current_var), line)
                if val_match:
                    value = val_match.group(1).strip()
                    # Only track SRC_URI and SRCREV
                    if current_var == "SRC_URI":
                        recipes.setdefault(current_recipe or "unknown", {})["SRC_URI"] = value
                    elif current_var == "SRCREV":
                        recipes.setdefault(current_recipe or "unknown", {})["SRCREV"] = value
                    current_var = None
                continue

            # Detect PN (recipe name) assignment to track which recipe we're in
            pn_match = re.match(r'^PN="(.*)"$', line)
            if pn_match:
                current_recipe = pn_match.group(1).strip()

    return recipes


def extract_git_srcuris(src_uri_value):
    """
    Extract git:// URIs from a SRC_URI value.

    SRC_URI can contain multiple space-separated entries.
    We only care about git:// entries.

    Returns list of git URIs.
    """
    if not src_uri_value:
        return []

    # Split by whitespace, filter git:// entries
    entries = src_uri_value.split()
    git_entries = []
    current = None

    for entry in entries:
        if entry.startswith("git://"):
            if current:
                git_entries.append(current)
            current = entry
        elif current:
            # Append parameters to the current git URI
            current = current + " " + entry
        # Non-git standalone entries are ignored

    if current:
        git_entries.append(current)

    return git_entries


def extract_repo_name(git_uri):
    """
    Extract repository name from a git URI.

    git://github.com/openbmc/linux;protocol=https;branch=dev-6.6 -> linux
    git://github.com/openbmc/phosphor-dbus-interfaces;protocol=https -> phosphor-dbus-interfaces
    """
    # Split off parameters first
    url_part = git_uri.split(";")[0]

    # Get the last path component, strip .git suffix
    path = url_part.split(":")[-1]  # handle git://host/path and ssh://host/path
    if path.startswith("//"):
        path = path[2:]

    repo_name = path.split("/")[-1]
    if repo_name.endswith(".git"):
        repo_name = repo_name[:-4]

    return repo_name


def convert_to_https_url(git_uri):
    """
    Convert a git:// URI with parameters to an https:// clone URL.

    git://github.com/openbmc/linux;protocol=https;branch=dev-6.6
    -> https://github.com/openbmc/linux

    If the URI already contains protocol=https, use https.
    Otherwise default to https for github.com URLs.
    """
    url_part = git_uri.split(";")[0]
    params = git_uri.split(";")[1:]

    # Extract host and path from git:// URI
    if url_part.startswith("git://"):
        rest = url_part[6:]  # strip git://
    elif url_part.startswith("https://"):
        return url_part
    elif url_part.startswith("ssh://"):
        # Convert ssh://git@github.com/... to https://github.com/...
        rest = url_part[6:]
        if rest.startswith("git@"):
            rest = rest[4:]
        return "https://" + rest
    else:
        return url_part

    return "https://" + rest


def main():
    args = parse_args()

    if not os.path.isfile(args.pn_buildlist):
        print(f"Error: pn-buildlist not found: {args.pn_buildlist}", file=sys.stderr)
        sys.exit(1)

    if not os.path.isfile(args.bitbake_env):
        print(f"Error: bitbake-env not found: {args.bitbake_env}", file=sys.stderr)
        sys.exit(1)

    # Read the list of recipes that bitbake would build
    recipe_names = read_file_lines(args.pn_buildlist)

    # Parse bitbake -e output for variable values
    env_vars = parse_bitbake_env(args.bitbake_env)

    # Build output: one entry per git-based recipe
    results = []
    seen_repos = set()

    for recipe in recipe_names:
        recipe_info = env_vars.get(recipe, {})
        src_uri = recipe_info.get("SRC_URI", "")
        srcrev = recipe_info.get("SRCREV", "AUTOINC")

        git_uris = extract_git_srcuris(src_uri)
        if not git_uris:
            continue

        for git_uri in git_uris:
            repo_name = extract_repo_name(git_uri)

            # Deduplicate by repo name (some recipes share the same repo)
            if repo_name in seen_repos:
                continue
            seen_repos.add(repo_name)

            results.append(
                {
                    "name": repo_name,
                    "src_uri": git_uri,
                    "srcrev": srcrev if srcrev != "AUTOINC" else "${AUTOREV}",
                    "recipe": recipe,
                    "clone_url": convert_to_https_url(git_uri),
                }
            )

    json.dump(results, sys.stdout, indent=2, ensure_ascii=False)
    print()  # trailing newline


if __name__ == "__main__":
    main()
